name: Build Android APK

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
      - 'Android/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'Android/**'

jobs:
  build_apk:
    name: Build Android APK
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Android/src
    steps:
      - name: Checkout the source code
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Make Gradle Executable
        run: chmod +x gradlew

      - name: Build Release APK
        run: ./gradlew assembleRelease

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          # Path to the generated APK - typically located in build/outputs/apk/release/
          path: Android/src/app/build/outputs/apk/release/*.apk
          retention-days: 7
